backend:
  name: github
  repo: nicodaniel/mariedet-blog
media_folder: content/assets
public_folder: /assets
collections:
  - name: blog
    label: "mariedet articles"
    folder: content/blog
    path: '{{slug}}/index'
    create: true
    fields:
      - { name: title, label: Title }
      - { name: topic, label: Topic, options: ["travel", "cycling", "training", "meet-up", "food"], widget: "select"}
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: "Title description" }
      - { name: preview, label: "Image preview", widget: "image"}
      - { name: body, label: Body, widget: markdown }
